# Development configuration
# This overrides settings in _config.yml for local development

# Local development settings
url: "http://localhost:4000"
baseurl: ""

# Show drafts and future posts in development
show_drafts: true
future: true

# Enable incremental regeneration for faster builds
incremental: true

# More verbose output for debugging
verbose: true
