# Development configuration for /next staging
# This overrides settings in _config.yml for local development

# Local development settings for next version
url: "http://localhost:4001"
baseurl: ""

# Show drafts and future posts in development
show_drafts: true
future: true

# Enable incremental regeneration for faster builds
incremental: true

# More verbose output for debugging
verbose: true
